/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libery_management_system1;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import com.mysql.cj.jdbc.MysqlDataSource;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.*; 
import javax.swing.*;
import net.proteanit.sql.DbUtils; 


/**
 *
 * @author sr computer
 */
public class catagory extends javax.swing.JFrame {

    /**
     * Creates new form catagory
     */
    public catagory() {
        initComponents();
         //catagory_load(); 
        
    }
    Connection conn;
    ResultSet rs; 
     PreparedStatement pst;
     
   
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_catagory = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txt_catagory1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Catagory");

        txt_catagory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Check Status : ");

        update.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        update.setText("Update ");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Catagory_name", "Status", "Self_number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Self Number:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txt_catagory1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText(" Book Catagory Name :  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(469, 469, 469)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_catagory, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_catagory1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2)
                        .addGap(130, 130, 130)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_catagory1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_catagory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        main_Frame ln = new main_Frame();
        ln.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
       String name=txt_catagory1.getText(); 
       String status=txt_catagory.getText(); 
       String self_number=jTextField2.getText(); 
        
        String url = "jdbc:mysql://localhost/";
        String dbname = "Details_library";
        String Driver = "com.mysql.jdbc.Driver";
        String username = "root";
        String password = "";
        try {
            Class.forName(Driver);
            java.sql.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(url + dbname, username, password);
            System.out.println("Connection is done ");
            
            String rul1="INSERT INTO `catagory_name`( `catname`, `status`, `Self_number`) VALUES (?,?,?)"; 
            pst=conn.prepareStatement(rul1); 
            pst.setString(1, name);
            pst.setString(2,status); 
            pst.setString(3, self_number);
            
             pst.execute();

            JOptionPane.showMessageDialog(this, "data insert");
            
            
            int c; 
            pst=conn.prepareStatement("SELECT * FROM `catagory_name`");
              ResultSet rs; 
           rs=pst.executeQuery(); 
           
           ResultSetMetaData rsd=rs.getMetaData(); 
           c=rsd.getColumnCount(); 
           DefaultTableModel d=(DefaultTableModel)jTable1.getModel(); 
           d.setRowCount(c); 
           while(rs.next())
           { 
               Vector v=new  Vector(); 
               for(int i=1;i<=c;i++)
               { 
                   v.add(rs.getString("id")); 
                    v.add(rs.getString("catname")); 
                     v.add(rs.getString("status")); 
                      v.add(rs.getString("Self_number")); 
                   
               }
              d.addRow(v);
           }
           txt_catagory.setText(null);
           txt_catagory1.setText(null);
           jTextField2.setText(null);
           
           conn.close();
         
             } catch (ClassNotFoundException ex) {
            //Logger.getLogger(database_1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Connection Failaa");
        } catch (SQLException ex) {
            //Logger.getLogger(database_1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Connection Fail");
        }
         

    }//GEN-LAST:event_addActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        
         try {
              DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
         int selectIndex=jTable1.getSelectedRow(); 
         int id=Integer.parseInt(d.getValueAt(selectIndex,0).toString()); 
         //txt_catagory3.setText(d.getValueAt(selectIndex, 0).toString());
            txt_catagory1.setText(d.getValueAt(selectIndex, 1).toString());
               txt_catagory.setText(d.getValueAt(selectIndex, 2).toString());
                  jTextField2.setText(d.getValueAt(selectIndex, 3).toString());
                  add.setEnabled(false);
         }catch(NullPointerException ex )
         { 
             JOptionPane.showMessageDialog(null, ex);
             
         }
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
         int selectIndex=jTable1.getSelectedRow(); 
         int id=Integer.parseInt(d.getValueAt(selectIndex,0).toString()); 
        
      String name=txt_catagory1.getText(); 
       String status=txt_catagory.getText(); 
       String self_number=jTextField2.getText(); 
        
        String url = "jdbc:mysql://localhost/";
        String dbname = "Details_library";
        String Driver = "com.mysql.jdbc.Driver";
        String username = "root";
        String password = "";
        try {
            Class.forName(Driver);
            java.sql.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(url + dbname, username, password);
            System.out.println("Connection is done ");
            
            String rul1="UPDATE `catagory_name` SET `catname`=?,`status`=?,`Self_number`=? WHERE `id`=?"; 
            pst=conn.prepareStatement(rul1); 
            pst.setString(1, name);
            pst.setString(2,status); 
            pst.setString(3, self_number);
            pst.setInt(4, id);
            
             pst.execute();

            JOptionPane.showMessageDialog(this, "data updated");
            
            
            int c; 
            pst=conn.prepareStatement("SELECT * FROM `catagory_name`");
              ResultSet rs; 
           rs=pst.executeQuery(); 
           
           ResultSetMetaData rsd=rs.getMetaData(); 
           c=rsd.getColumnCount(); 
          // DefaultTableModel d=(DefaultTableModel)jTable1.getModel(); 
           d.setRowCount(c); 
           while(rs.next())
           { 
               Vector v=new  Vector(); 
               for(int i=1;i<=c;i++)
               { 
                   v.add(rs.getString("id")); 
                    v.add(rs.getString("catname")); 
                     v.add(rs.getString("status")); 
                      v.add(rs.getString("Self_number")); 
                   
               }
              d.addRow(v);
           }
           txt_catagory.setText(null);
           txt_catagory1.setText(null);
           jTextField2.setText(null);
           add.setEnabled(true);
           conn.close();
         
             } catch (ClassNotFoundException ex) {
            //Logger.getLogger(database_1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Connection Failaa");
        } catch (SQLException ex) {
            //Logger.getLogger(database_1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Connection Fail");
        }
         
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
         int selectIndex=jTable1.getSelectedRow(); 
         int id=Integer.parseInt(d.getValueAt(selectIndex,0).toString()); 
        
      
        
        String url = "jdbc:mysql://localhost/";
        String dbname = "Details_library";
        String Driver = "com.mysql.jdbc.Driver";
        String username = "root";
        String password = "";
        try {
            Class.forName(Driver);
            java.sql.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(url + dbname, username, password);
            System.out.println("Connection is done ");
            
            String rul1="DELETE FROM `catagory_name` WHERE `id`=?"; 
            pst=conn.prepareStatement(rul1); 
           
            pst.setInt(1, id);
            
             pst.execute();

            JOptionPane.showMessageDialog(this, "data insert");
            
            
            int c; 
            pst=conn.prepareStatement("SELECT * FROM `catagory_name`");
              ResultSet rs; 
           rs=pst.executeQuery(); 
           
           ResultSetMetaData rsd=rs.getMetaData(); 
           c=rsd.getColumnCount(); 
          // DefaultTableModel d=(DefaultTableModel)jTable1.getModel(); 
           d.setRowCount(c); 
           while(rs.next())
           { 
               Vector v=new  Vector(); 
               for(int i=1;i<=c;i++)
               { 
                   v.add(rs.getString("id")); 
                    v.add(rs.getString("catname")); 
                     v.add(rs.getString("status")); 
                      v.add(rs.getString("Self_number")); 
                   
               }
              d.addRow(v);
           }
           txt_catagory.setText(null);
           txt_catagory1.setText(null);
           jTextField2.setText(null);
           add.setEnabled(true);
           conn.close();
         
             } catch (ClassNotFoundException ex) {
            //Logger.getLogger(database_1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Connection Failaa");
        } catch (SQLException ex) {
            //Logger.getLogger(database_1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Connection Fail");
        }
      
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catagory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txt_catagory;
    private javax.swing.JTextField txt_catagory1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
